// <auto-generated />
using System;
using MarketAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MKPUC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketAPI.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfficialProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomProductId");

                    b.HasIndex("OfficialProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MarketAPI.Entities.CustomProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("CustomProducts");
                });

            modelBuilder.Entity("MarketAPI.Entities.OfficialProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("OfficialProducts");
                });

            modelBuilder.Entity("MarketAPI.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("MarketAPI.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("MarketAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarketAPI.Entities.UserProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserProviders");
                });

            modelBuilder.Entity("MarketAPI.RelationalEntities.UserShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.HasIndex("UserId");

                    b.ToTable("UserShoppingCarts");
                });

            modelBuilder.Entity("MarketAPI.Entities.CartItem", b =>
                {
                    b.HasOne("MarketAPI.Entities.CustomProduct", "CustomProduct")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketAPI.Entities.OfficialProduct", "OfficialProduct")
                        .WithMany("CartItems")
                        .HasForeignKey("OfficialProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketAPI.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomProduct");

                    b.Navigation("OfficialProduct");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("MarketAPI.Entities.CustomProduct", b =>
                {
                    b.HasOne("MarketAPI.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("CustomProducts")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MarketAPI.Entities.OfficialProduct", b =>
                {
                    b.HasOne("MarketAPI.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("OfficialProducts")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MarketAPI.Entities.ShoppingCart", b =>
                {
                    b.HasOne("MarketAPI.Entities.User", "CreatedByUser")
                        .WithMany("CreatedCarts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MarketAPI.Entities.UserProvider", b =>
                {
                    b.HasOne("MarketAPI.Entities.User", "User")
                        .WithMany("UserProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAPI.RelationalEntities.UserShoppingCart", b =>
                {
                    b.HasOne("MarketAPI.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("UserShoppingCarts")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketAPI.Entities.User", "User")
                        .WithMany("UserShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketAPI.Entities.CustomProduct", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MarketAPI.Entities.OfficialProduct", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MarketAPI.Entities.ShoppingCart", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("UserShoppingCarts");
                });

            modelBuilder.Entity("MarketAPI.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("CustomProducts");

                    b.Navigation("OfficialProducts");
                });

            modelBuilder.Entity("MarketAPI.Entities.User", b =>
                {
                    b.Navigation("CreatedCarts");

                    b.Navigation("UserProviders");

                    b.Navigation("UserShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
